# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
    branches:
        include:
        - master
        - refs/tags/*
    tags:
        include:
        - v*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run tests'

- script: |
    pip install wheel
    python setup.py sdist bdist_wheel
  displayName: 'Artifact creation'
  

- task: PublishPipelineArtifact@0
  condition: eq(variables['python.version'], '3.7')  # Only publish artifacts passing Py37
  inputs:
      artifactName: 'dataflow-cookiecutter-artifact'
      targetPath: 'dist'
  displayName: 'Publish pipeline artifact'

- task: GithubRelease@0
  inputs:
      gitHubConnection: dataflow-cookiecutter-release
      repositoryName: '$(build.Repository.Name)'
      assets: dist/*
      addChangeLog: true
      compareWith: 'lastRelease'
  displayName: 'Create Github release'
